### ISSUE TITLE
Exception in castep parser

### ISSUE THREAD

**Issue by markus1978** [nomad-coe/nomad-parser-castep#1]
This happens on 6 entries.

```
Traceback (most recent call last):
  File "/app/nomad/processing/data.py", line 460, in parsing
    self._parser_results, logger=logger)
  File "/usr/local/lib/python3.7/site-packages/castepparser/castep_parser.py", line 1200, in parse
    self.parse_configurations()
  File "/usr/local/lib/python3.7/site-packages/castepparser/castep_parser.py", line 1051, in parse_configurations
    parse_calculation(calculation)
  File "/usr/local/lib/python3.7/site-packages/castepparser/castep_parser.py", line 1045, in parse_calculation
    sec_scc = parse_scc(source)
  File "/usr/local/lib/python3.7/site-packages/castepparser/castep_parser.py", line 957, in parse_scc
    sec_sedc.x_castep_correction_energy = (shell[1] * energy_unit).to('J').magnitude
  File "/usr/local/lib/python3.7/site-packages/pint/quantity.py", line 660, in to
    magnitude = self._convert_magnitude_not_inplace(other, *contexts, **ctx_kwargs)
  File "/usr/local/lib/python3.7/site-packages/pint/quantity.py", line 609, in _convert_magnitude_not_inplace
    return self._REGISTRY.convert(self._magnitude, self._units, other)
  File "/usr/local/lib/python3.7/site-packages/pint/registry.py", line 947, in convert
    return self._convert(value, src, dst, inplace)
  File "/usr/local/lib/python3.7/site-packages/pint/registry.py", line 1830, in _convert
    return super()._convert(value, src, dst, inplace)
  File "/usr/local/lib/python3.7/site-packages/pint/registry.py", line 1433, in _convert
    return super()._convert(value, src, dst, inplace)
  File "/usr/local/lib/python3.7/site-packages/pint/registry.py", line 996, in _convert
    value = value * factor
TypeError: can't multiply sequence by non-int of type 'float'
```

The example has embargo on it. 
https://nomad-lab.eu/prod/rae/reprocess/gui/entry/id/CTTru-A7REe4XWGaV-l3cA/s47fvrWr7RNl7TnmonHs7xQY0WMe/raw

**Comment by markus1978** [comment]
@ladinesa I reprocessed the castep entries. Looks good. That was the only apparent exception.

**Comment by ladinesa** [comment]
Should be fixed in latest commit.
